---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Add entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }}"
    create: true
    state: present
    regexp: '^127\.0\.1\.1\s+{{ inventory_hostname }}'