---
- name: Disable swap
  command: swapoff -a
  changed_when: false
  become: true

- name: Comment out swap in fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^(/.*swap.*)$'
    line: '# \1'
    backrefs: yes
    state: present
  become: true

- name: Configure kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  become: true

- name: Configure sysctl
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  become: true

- name: Apply sysctl
  command: sysctl --system
  become: true

- name: Ensure keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
  become: true

- name: Download and import Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes
  become: true

- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubectl
      - kubeadm
      - containerd
    state: present
    update_cache: yes
  become: true

- name: Hold Kubernetes packages
  shell: |
    apt-mark hold kubelet kubectl kubeadm
  become: true

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce
    update_cache: yes
  become: true

- name: Install containerd from Docker repo
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  become: true

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  become: true

- name: Configure SystemdCgroup in containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup\s*=\s*false'
    replace: 'SystemdCgroup = true'
  become: true

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
  become: true

- name: Configure kubelet cgroup driver
  lineinfile:
    path: /etc/default/kubelet
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd'
    create: yes
    mode: 0644
  become: true

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started
  become: true

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  become: true

- name: Restart SSH service
  systemd:
    name: ssh
    state: restarted
    daemon_reload: yes
  become: true