---
- name: Get join command from primary control node
  slurp:
    src: /tmp/worker-join-command
  register: worker_join_command
  delegate_to: "{{ hostvars[primary_control_node_for_delegation]['ansible_hostname'] }}"

- name: Join worker nodes to cluster
  command: "{{ worker_join_command.content | b64decode }}"
  async: 120
  poll: 10
  become: true