# Filepath: ./roles/control/tasks/init-cluster.yml
- name: Ensure kubeadm config directory exists
  file:
    path: /root
    state: directory
    mode: 0755
  become: true

- name: Copy kubeadm config template to control plane nodes
  template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml
    mode: 0644
  become: true

- name: Initialize first control plane
  command: kubeadm init --config /root/kubeadm-config.yaml --upload-certs --ignore-preflight-errors=all
  when: inventory_hostname == "node1"
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

- name: Setup kubeconfig for root user
  block:
    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: 0750

    - name: Copy admin config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root
        group: root
        mode: 0600
  when: inventory_hostname == "node1"
  become: true

- name: Install CNI plugin (Calico)
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
  when: inventory_hostname == "node1"
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf