---
- name: Check if cluster is initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: cluster_initialized
  become: true

- name: Initialize primary control plane
  command: |
    kubeadm init \
      --control-plane-endpoint "{{ primary_control_ip }}" \
      --pod-network-cidr=10.244.0.0/16 \
      --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  when: 
    - inventory_hostname == primary_control_node
    - not cluster_initialized.stat.exists
  become: true
  register: init_result

- name: Save admin config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  when: inventory_hostname == primary_control_node
  become: true

- name: Install Flannel CNI
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: inventory_hostname == primary_control_node
  become: true

- name: Generate join command (control plane)
  command: kubeadm token create --print-join-command
  register: control_join_command
  when: inventory_hostname == primary_control_node
  become: true

- name: Save control plane join command
  copy:
    content: "{{ control_join_command.stdout }}"
    dest: /tmp/control-join-command
    mode: 0600
  when: inventory_hostname == primary_control_node
  become: true

- name: Get join command for secondary control nodes
  slurp:
    src: /tmp/control-join-command
  register: control_join_command
  when: inventory_hostname != primary_control_node
  delegate_to: "{{ primary_control_node }}"

- name: Join control plane nodes
  command: "{{ control_join_command.content | b64decode }} --control-plane"
  when: inventory_hostname != primary_control_node
  become: true