---
# 1. System Preparation
- name: Install prerequisites
  apt:
    name: [curl, gnupg2, software-properties-common, apt-transport-https, ca-certificates]
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Permanent swap disable
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s.*)$'
    replace: '# \1'

- name: Configure kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Configure sysctl
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  register: sysctl

- name: Apply sysctl
  command: sysctl --system
  when: sysctl.changed

# 2. Container Runtime Setup
- name: Configure containerd
  shell: |
    containerd config default | tee /etc/containerd/config.toml >/dev/null
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
    systemctl restart containerd

# 4. Cluster Initialization
- name: Initialize cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configure kubectl
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

# 5. Network Setup
- name: Install Flannel network plugin
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    creates: /etc/kubernetes/manifests/kube-flannel-ds.yaml

- name: Taint master node
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  when: inventory_hostname == "node1"

# 6. Join Command Handling
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false
  delegate_to: node1
  run_once: true

- name: Store join command
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join-command
    mode: 0755