- name: Get join command from control plane
  command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: node_0
  run_once: yes

- name: Join worker to cluster
  command: "{{ join_command.stdout }}"
