---
- name: Configure Common
  hosts: all
  become: yes
  roles:
    - role: common
      tags: [common]

- name: Configure Control Plane
  hosts: kube_control
  become: yes
  roles:
    - role: control
      tags: [control]

- name: Join Worker Nodes
  hosts: kube_node
  become: yes
  roles:
    - role: worker
      tags: [worker]